[package]
name = "clickhouse-driver-derive"
version = "0.1.1"
description = "Derive macros for ClickHouse Asynchronous Driver."
authors = ["Dmitry Dulesov <dmitry.dulesov@gmail.com>"]
edition = "2018"

[dependencies]
syn = "1.0.84"
quote = "1.0.14"
proc-macro2 = "1.0.36"

[lib]
proc-macro = true
